addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - libatlas-base-dev
      - libatlas-dev
      - libblas-dev
      - libgtk-3-dev
      - libhdf5-serial-dev
      - liblapack-dev
      - libpng-dev
      - libtiff4-dev
      - libwxgtk2.8-dev
      - libxml2-dev
      - libxslt1-dev
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dask h5py libtiff lxml matplotlib MySQL-python networkx numpy pandas pyzmq scikit-image scikit-learn scipy wxpython
  - source activate test-environment
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
env:
  - CP_MYSQL_TEST_HOST=127.0.0.1 CP_MYSQL_TEST_PASSWORD=None CP_MYSQL_TEST_USER=travis LC_ALL=en_US.UTF-8
install:
  - python setup.py install
language: python
python:
  - 2.7
script: python setup.py test -a -x
services:
  - mysql
sudo: false
